from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "SpyV2Beta.lua"
OUT = ROOT / "dist" / "SpyV2Beta.lua"
HIGHLIGHT = ROOT / "vendor" / "Highlight.lua"
DATATOCODE = ROOT / "vendor" / "DataToCode.lua"
MODERN_UI = ROOT / "tools" / "SingleFileUI.lua"


def embed_module(name: str, source: str) -> str:
    return (
        f"\n-- ===== VENDORED DEPENDENCY: {name} =====\n"
        f"local {name} = (function()\n"
        f"{source}\n"
        f"end)()\n"
        f"-- ===== END VENDORED DEPENDENCY: {name} =====\n"
    )


def replace_legacy_dependencies(source: str, highlight: str, datatocode: str) -> str:
    # Match the actual loader block by its two upstream URL literals rather
    # than relying on the placeholder text. This avoids producing a partial
    # package if the legacy loader changes shape later.
    pattern = re.compile(
        r"local Highlight = .*?"
        r"local LazyFix = .*?"
        r"\n\s*pcall\(function\(\).*?"
        r"raw\.githubusercontent\.com/78n/SimpleSpy/main/Highlight\.lua.*?"
        r"\nend\)\s*"
        r"pcall\(function\(\).*?"
        r"raw\.githubusercontent\.com/78n/Roblox/refs/heads/main/Lua/Libraries/DataToCode/DataToCode\.luau.*?"
        r"\nend\)",
        re.S,
    )

    match = pattern.search(source)
    if not match:
        raise SystemExit(
            "Legacy external dependency loader block was not found; "
            "refusing to produce a partial package."
        )

    replacement = embed_module("Highlight", highlight) + embed_module("LazyFix", datatocode)
    return source[: match.start()] + replacement + source[match.end() :]


def main():
    source = SOURCE.read_text(encoding="utf-8")
    highlight = HIGHLIGHT.read_text(encoding="utf-8")
    datatocode = DATATOCODE.read_text(encoding="utf-8")
    modern_ui = MODERN_UI.read_text(encoding="utf-8")

    source = replace_legacy_dependencies(source, highlight, datatocode)

    packaged = (
        "--!native\n"
        "-- SIMPLESPY SINGLE-FILE PACKAGE\n"
        "-- Generated by tools/package.py.\n\n"
        + source
        + "\n\n-- ===== MODERN SINGLE-FILE UI =====\n"
        + modern_ui
        + "\n-- ===== END MODERN SINGLE-FILE UI =====\n"
    )

    # Fail closed if either external dependency URL survived the replacement.
    for forbidden in (
        "https://raw.githubusercontent.com/78n/SimpleSpy/main/Highlight.lua",
        "https://raw.githubusercontent.com/78n/Roblox/refs/heads/main/Lua/Libraries/DataToCode/DataToCode.luau",
    ):
        if forbidden in packaged:
            raise SystemExit(f"External dependency URL remains in package: {forbidden}")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(packaged, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(packaged):,} bytes)")


if __name__ == "__main__":
    main()
