from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "SpyV2Beta.lua"
OUT = ROOT / "dist" / "SpyV2Beta.lua"
HIGHLIGHT = ROOT / "vendor" / "Highlight.lua"
DATATOCODE = ROOT / "vendor" / "DataToCode.lua"
MODERN_UI = ROOT / "tools" / "SingleFileUI.lua"


def embed_module(name: str, source: str) -> str:
    return (
        f"\n-- ===== VENDORED DEPENDENCY: {name} =====\n"
        f"local {name} = (function()\n"
        f"{source}\n"
        f"end)()\n"
        f"-- ===== END VENDORED DEPENDENCY: {name} =====\n"
    )


def main():
    source = SOURCE.read_text(encoding="utf-8")
    highlight = HIGHLIGHT.read_text(encoding="utf-8")
    datatocode = DATATOCODE.read_text(encoding="utf-8")
    modern_ui = MODERN_UI.read_text(encoding="utf-8")

    # Replace the two network dependency loaders in the legacy file.
    dependency_pattern = re.compile(
        r'local Highlight = \{ new = function\(\) return \{ setRaw = function\(\) end, getString = function\(\) return "" end \} end \}\n'
        r'local LazyFix = \{ Convert = function\(a\) return tostring\(a\) end, ConvertKnown = function\(a,b\) return "game" end \}\n'
        r'\npcall\(function\(\)\n.*?\nend\)\n\s*pcall\(function\(\)\n.*?\nend\)',
        re.S,
    )

    if not dependency_pattern.search(source):
        raise SystemExit("Dependency loader block was not found; refusing to produce a partial package.")

    source = dependency_pattern.sub(
        embed_module("Highlight", highlight) + embed_module("LazyFix", datatocode),
        source,
        count=1,
    )

    # Keep the legacy interception/addon system intact and append the rebuilt UI
    # as the presentation layer. The appended layer disables the old GUI and
    # reuses the legacy logs, serializer, blacklist/blocklist and config state.
    packaged = (
        "--!native\n"
        "-- SIMPLESPY SINGLE-FILE PACKAGE\n"
        "-- Generated by tools/package.py.\n\n"
        + source
        + "\n\n-- ===== MODERN SINGLE-FILE UI =====\n"
        + modern_ui
        + "\n-- ===== END MODERN SINGLE-FILE UI =====\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(packaged, encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(packaged):,} bytes)")


if __name__ == "__main__":
    main()
